# Questão 1

Nessa primeira questão o Du quer que a gente teste o erro 404 do endpoint PUT.
Temos esse código em questão:
```py
@app.put('/users/{user_id}', response_model=UserPublic)
def update_user(user_id: int, user: UserSchema):
    if user_id > len(database) or user_id < 1:
        raise HTTPException(status_code=404, detail='User not found')

    user_with_id = UserPublic(**user.model_dump(), id=user_id)
    database[user_id - 1] = user_with_id

    return UserPublic(**user_with_id.model_dump())
```

Para entrar no if do endpoint podemos ou passar um id maior que a quantidade de
usuários no nosso banco de dados provisório ou colocar um id menor que 1.
Nessa questão em específico vou chamar o id igual a 0

```py
def test_error_update_user_index_out_of_range(client):
    response = client.put(
        '/users/0',
        json={
            'username': 'bob',
            'email': 'bob@example.com',
            'password': 'mynewpassword',
        },
    )
    assert response.status_code == 404
    assert response.json() == {'detail': 'User not found'}
```
Dessa forma com o `user_id` igual a 0 ele entra no if da exceção.
