# Questão 3
Temos que criar um novo endpoint com GET que retorna um único usuário e por fim
fazer o teste desse endpoint.

#### Criando o endpoint.

Para criar isso vamos passar como parâmetro na rota o `user_id`, assim como ocorreu
no desenvolvimento dos endpoints de PUT e DELETE, para especificar o usuário.

Como podemos ver aqui:
```py
@app.get('/users/{user_id}', response_model=UserPublic)
def read_user(user_id: int):
    if user_id > len(database) or user_id < 1:
        raise HTTPException(status_code=404, detail='User not found')

    user = database[user_id-1]

    return user
```

Faço a verificação do `user_id` para evitar qualquer erro no acesso ao banco de
dados provisório. Após isso pego acho o `user` fazendo a busca por index e retorno
esse `user`.
Vale a ressaltar que o o modelo de reposta será `UserPublic`, pois será apenas um
usuário retornado.


#### Testando nosso novo endpoint.
Para fazer esse validação iremos criar dois novos testes, um para ver se nosso
endpoint está funcionando da forma apropriada e outro para ver se a exceção para
testarmos a exceção.


##### Para o nosso primeiro teste
Como criamos a Alice com um POST anteriormente, podemos verificar agora apenas a
existência dela com esse endpoint, dessa forma:
```py
def test_read_user(client):
    response = client.get('/users/1')
    assert response.status_code == 200
    assert response.json() == {
        'username': 'alice',
        'email': 'alice@example.com',
        'id': 1,
    }
```

##### Já o segundo teste
Sendo uma abordagem parecida com as outras duas questões devemos chamar um index
que não existe, nesse caso em especifico irei usar com o index igual 0.
```py
def test_error_read_user_index_out_of_range(client):
    response = client.get('/users/0')
    assert response.status_code == 404
    assert response.json() == {'detail': 'User not found'}
```

Com isso finalizamos as questões com 100% de covarage e com o novo endpoint implementado
e testado.
