# Questão 3

Nessa próxima questão temos que implementar novamente o endpoint usando o GET,
onde conseguimos as informações do usuário baseado no id dele. Vamos relembrar
como foi implementado o nossa logica:
```py
@app.get('/users/{user_id}', response_model=UserPublic)
def read_user(user_id: int):
    if user_id > len(database) or user_id < 1:
        raise HTTPException(status_code=404, detail='User not found')

    user = database[user_id-1]

    return user
```

Podemos nos inspirar na forma que foi escrito a logica do endpoint que o Duno usou
para escrever o enpoint GET da routa `/users/`, como podemos ver aqui:

```py
@app.get('/users/', response_model=UserList)
def read_users(
    skip: int = 0, limit: int = 100, session: Session = Depends(get_session)
):
    users = session.scalars(select(User).offset(skip).limit(limit)).all()
    return {'users': users}
```
Porém não precisamos de tanto parâmetros que foram passados, pois eles são de
controle para um grande volume de dados e no nosso caso queremos apenas um usuário,
dessa forma fica assim nosso novo endpoint:
```py
@app.get('/users/{user_id}', response_model=UserPublic)
def read_user(user_id: int, session: Session = Depends(get_session)):
    db_user = session.scalar(select(User).where(User.id == user_id))
    if not db_user:
        raise HTTPException(status_code=404, detail='User not found')

    return db_user
```
Vale ressaltar que eu criei essa exceção caso a gente não encontre o usuário na
query do banco de dados. Mudei também o `response_model` para ser do tipo usuário
publico nosso schema.

Agora precisamos testar se o endpoint está funcionando da forma correta.
Para fazer a usaremos a mesma lógica dos testes passados, dessa forma:
```py
def test_read_user_with_users(client, user):
    user_schema = UserPublic.model_validate(user).model_dump()
    response = client.get('/users/1')

    assert response.json() == user_schema
```
Criamos nosso usuário no banco de dados de teste e fazemos a requisição do mesmo
e validamos no final.

Para testar a exceção fazemos a chamada do mesmo index entretanto não utilizei
a fixture do users para não criar nenhum usuário no banco de dados, ficando dessa
forma:
```py
def test_error_read_user_with_users(client):
    response = client.get('/users/0')

    assert response.status_code == 404
    assert response.json() == {'detail': 'User not found'}
```
Com isso conseguimos criar um novo endpoint além de conseguir 100% de coverage
no nosso app.
